sudo: false
language: python
install:
  - "pip install tox"
script:
  - "tox"
env:
  - "TOXENV=py34-1.10.X"
  - "TOXENV=py27-1.10.X"
  - "TOXENV=py34-1.9.X"
  - "TOXENV=py27-1.9.X"
  - "TOXENV=py34-1.8.X"
  - "TOXENV=py27-1.8.X"
  - "TOXENV=py34-1.7.X"
  - "TOXENV=py27-1.7.X"
  - "TOXENV=py34-1.6.X"
  - "TOXENV=py27-1.6.X"
  - "TOXENV=py34-2.0.X"
  - "TOXENV=py34-1.11.X"
  - "TOXENV=py27-1.11.X"
matrix:
  allow_failures:
  - env: "TOXENV=py34-2.0.X"
  - env: "TOXENV=py34-1.11.X"
  - env: "TOXENV=py27-1.11.X"
  fast_finish: true
cache:
  directories:
    - $HOME/.cache/pip
